-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 15:02:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chatting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatting` DEFAULT CHARACTER SET utf8 ;
USE `chatting` ;

-- -----------------------------------------------------
-- Table `chatting`.`chatting_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatting`.`chatting_log` (
  `sendId` VARCHAR(10) NOT NULL,
  `sendContents` TEXT NULL,
  PRIMARY KEY (`sendId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
